[package]
name = "tpc9000/rosyn"
version = "0.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors = ["tpc9000"]

[dependencies]
TypeGuard = "tpc9000/typeguard@2.2.0"
Cleaner = "tpc9000/cleaner@0.1.1"
XSignal = "tpc9000/xsignal@0.1.0"