[package]
name = "tpc9000/rosyn"
version = "0.4.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors = ["tpc9000"]

[dependencies]
TypeGuard = "tpc9000/typeguard@5.0.0"
TableUtil = "tpc9000/tableutil@0.6.0"
XSignal = "tpc9000/xsignal@2.0.0"
Async = "tpc9000/async@0.2.1"